# Generated by Django 5.2.7 on 2025-10-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
